[project]
authors = ["Sai Krishna Sunkari"]
entry = "main.sw"
license = "Apache-2.0"
name = "counter-contract"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.5.1" }

[proxy]
enabled = true
address = "0x35d1c8fbc9c2ca331f5ac9d469ba728d8480d3db13f893dcc8bc97cc6a91dee4"
